### ISSUE TITLE
Overall better styling of the page

### ISSUE THREAD

**Issue by bacloud14** [bacloud14/WeatherVenue#1]
I believe style is horrible and I need a helping hand.
It would be great if it supports **Mobile phones**. I see it as a single page web app where **weather forecasts** just resides besides the map. 
A **footer** and a **header** would be nice. 
Resize support for different screens would be nice too.

Please keep it simple, simple design is better, no flashy colors x)

Do not hesitate to add attributions for your GitHub (in footer?).

**Comment by bacloud14** [comment]
One bug is:
in div id=featured_picture. background image is well loaded although the div does not appear.

**Comment by bacloud14** [comment]
Bug: 
background repeat is applied to body, while the body is not stretched to content for some reason, background is not repeated to the bottom.

**Comment by dksmith328** [comment]
Hey there. I will get started on this today. Sorry about that wait.

**Comment by bacloud14** [comment]
Hey David, I appreciate that ! take your time, thank you so much !
Please do fetch/pull as much has been done since then.

**Comment by bacloud14** [comment]
ok, did you try with the same origin that I set on cloud account? which is localhost:3000

**Comment by dksmith328** [comment]
Yes sir. I can see the page. The map just doesn’t load.    Sent from Mail for Windows 10 From: AbenSent: Thursday, January 28, 2021 12:30 PMTo: bacloud14/SunnySundayCc: dksmith328; AssignSubject: Re: [bacloud14/SunnySunday] Overall better styling of the page (#1) ok, did you try with the same origin that I set on cloud account? which is localhost:3000—You are receiving this because you were assigned.Reply to this email directly, view it on GitHub, or unsubscribe.

**Comment by bacloud14** [comment]
You need a billing account though , so that the key work

**Comment by dksmith328** [comment]
I found a work around and just hardcoded the key into the url on index.html. I will make sure to conceal it again before I send it over to you.Sent from Mail for Windows 10 From: AbenSent: Thursday, January 28, 2021 12:39 PMTo: bacloud14/SunnySundayCc: dksmith328; AssignSubject: Re: [bacloud14/SunnySunday] Overall better styling of the page (#1) probably this is another error, you can check console for Google API errors.—You are receiving this because you were assigned.Reply to this email directly, view it on GitHub, or unsubscribe.

**Comment by bacloud14** [comment]
ahh I get you, in fact, I was doing it that way, there is no rendering involved. in reality there is no workaround, they will definitely end-up in user browser, this is how these client libraries work.
I suggested a minor improvement [here ](https://github.com/googlemaps/google-maps-services-js/issues/551#event-4261558204) today, it happens it is complicated to evolve to this ...

**Comment by bacloud14** [comment]
I think the confusion came from my side, the .env file, where I put the Google map key which is not used to render on client side at all.

**Comment by samy1998** [comment]
Hello, I would like to work on your project in order to improve it. I am currently a student in my 3rd year computer science degree in France.

**Comment by bacloud14** [comment]
Hello Samy, sure! You are very welcome. This issue is assigned to @dksmith328  and me for the moment. From my previous experience, working on style in the same time yields a hell of conflicts. 
So, I suggest you take a look on other issues for now until @dksmith328 pushes some improvements.

**Comment by bacloud14** [comment]
If you like design the most, just wait and we see.

**Comment by samy1998** [comment]
I will wait otherwise I will look at the other possible contributions

**Comment by bacloud14** [comment]
@samy1998 please see this https://github.com/bacloud14/SunnySunday/issues/6

Of course you contribute as you wish.

**Comment by bacloud14** [comment]
Keeping this open for some time.
For quick tests on browser console here is a new dummy version https://bacloud14.github.io/WeatherVenue/ without deployment !

**Comment by dksmith328** [comment]
Wow! This is really great. I love the full-screen view. Just wanted to let you know my progress. As much as I love the gradient, I was not able to make it work responsively. It also did not work with the Dark Mode, so I readjusted the color for the backgrounds, but I think they look nice. I added the container at the top for languages and added the Arabic page. I added space for the gallery. I am attempting to add a header for the gallery so the user knows what is going on. I will push those changes to you soon to see what you think.  Good job! The site is great.  -Daniel  Sent from Mail for Windows 10 From: baSent: Monday, February 8, 2021 7:22 AMTo: bacloud14/WeatherVenueCc: dksmith328; MentionSubject: Re: [bacloud14/WeatherVenue] Overall better styling of the page (#1) Keeping this open for some time.For quick tests on browser console here is a new dummy version https://bacloud14.github.io/WeatherVenue/ without deployment !—You are receiving this because you were mentioned.Reply to this email directly, view it on GitHub, or unsubscribe.

**Comment by bacloud14** [comment]
Great to hear ! I am so excited for it. take your time.
Could you make forecast weather cards appear in one row in desktop (size like) and one after the other (in many rows) for mobile (size like) devices ?
That would be great but please this is not a necessity. we already have much improvements from your side at a time. I can try myself too.

**Comment by dksmith328** [comment]
Yes. I was worried about a mobile version. But I will figure something out.  Sent from Mail for Windows 10 From: baSent: Monday, February 8, 2021 9:34 AMTo: bacloud14/WeatherVenueCc: dksmith328; MentionSubject: Re: [bacloud14/WeatherVenue] Overall better styling of the page (#1) Great to hear ! I am so excited for it. take your time.Could you make forecast weather cards appear in one row in desktop (size like) and one after the other (in many rows) for mobile (size like) devices ?That would be great but please this is not a necessity. we already have much improvements from your side at a time. I can try myself too.—You are receiving this because you were mentioned.Reply to this email directly, view it on GitHub, or unsubscribe.
