### ISSUE TITLE
Changing Language Redirecting to wrong Route

### ISSUE THREAD

**Issue by ME-ON1** [bacloud14/WeatherVenue#35]
It's currently Redirecting to `/fr` or `/ar` but it should be `/${pass}/ar`.

It will be a easy fix i guess,

**Comment by ME-ON1** [comment]
which leads to 404 page which is usual

**Comment by bacloud14** [comment]
Thank you for issuing this, I will check this later. Actually, ${pass} which is an empty string in prod and some random string in dev.

I thought of this simple security scheme  so that anyone who wants to contribute, would access any route as it is defined, plus his/her password.  Like for example:
`localhost:3000/fodjfoijodjjpofijq/ar`

This way, he/she can define an origin for keys for Google map or Openweathermap or anything, as : 
`localhost:3000/fodjfoijodjjpofijq/*`

Finally, other links messed up, like pictures ... So I will try to re-work it, or delete it at all.
thanks

**Comment by ME-ON1** [comment]
well, i can work in this issue !! 
can solved with conditional href attribute  for prod it can be `localhost:3000/fr` and for dev can be `localhost:3000/${pass}/fr`. If you want to keep pass in dev.

**Comment by bacloud14** [comment]
yes, absolutely that is the idea./ but that does for all resources, and also, I saw that -for some reason, when I go from `localhost/axxxxxx/` to `localhost/axxxxxx/ar` for example, other links would be like `localhost/axxxxxx/axxxxxx/fr` (which is inaccessible).

If you can work on it, thanks a lot ✌️ 😃 .

**Comment by bacloud14** [comment]
See this please, https://github.com/bacloud14/WeatherVenue/issues/36 if you want to add a placeholder and link back to https://github.com/bacloud14/WeatherVenue/graphs/contributors
